version: "3.8"
services:
  test:
    image: test
    container_name: "test-app"
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    container_name: "mongo_db"
    ports:
      - 27017:27017
